[View in Colaboratory](https://colab.research.google.com/github/DeepankJain/Machine-Learning/blob/master/Support%20Vector%20Machine/Support_Vector_Machine.ipynb)

In [0]:
#importing libraries
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [0]:
from sklearn.model_selection import train_test_split as tts
train, test = tts(iris, test_size = 0.2)

In [0]:
xtrain = train.loc[:, train.columns != 'species']
xtest = test.loc[:, test.columns != 'species']
ytrain = train['species']
ytest = test['species']

In [5]:
from sklearn.svm import SVC
model = SVC(kernel = 'poly', degree = 8)
model.fit(xtrain, ytrain)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [0]:
ypred = model.predict(xtest)

In [7]:
result = pd.DataFrame({'Actual': ytest, 'Predicted': ypred})
print(result)

         Actual   Predicted
133   virginica  versicolor
69   versicolor  versicolor
131   virginica   virginica
130   virginica   virginica
89   versicolor  versicolor
125   virginica   virginica
97   versicolor  versicolor
53   versicolor  versicolor
57   versicolor  versicolor
31       setosa      setosa
20       setosa      setosa
47       setosa      setosa
29       setosa      setosa
83   versicolor   virginica
76   versicolor  versicolor
77   versicolor  versicolor
65   versicolor  versicolor
11       setosa      setosa
148   virginica   virginica
118   virginica   virginica
44       setosa      setosa
135   virginica   virginica
1        setosa      setosa
94   versicolor  versicolor
32       setosa      setosa
35       setosa      setosa
146   virginica   virginica
105   virginica   virginica
18       setosa      setosa
143   virginica   virginica


In [9]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(ytest, ypred))

[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]


In [10]:
print(classification_report(ytest, ypred))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        10
 versicolor       0.90      0.90      0.90        10
  virginica       0.90      0.90      0.90        10

avg / total       0.93      0.93      0.93        30

