[View in Colaboratory](https://colab.research.google.com/github/DeepankJain/Machine-Learning/blob/master/Numpy/Linear_Algebra.ipynb)

In [0]:
import numpy as np

In [2]:
a = np.array([[2,3,4],[1,9,7]])
print(a)

[[2 3 4]
 [1 9 7]]


In [5]:
print(a.shape)

(2, 3)


In [7]:
a = np.zeros((2,3))
print(a)
b= np.ones((2,4))
print(b)
c = np.full((3,6), np.pi )
print(c)
d = np.eye(5)
print(d)
e = np.random.random((3,5))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.88776518 0.43625076 0.08300144 0.71595222 0.44701665]
 [0.37730095 0.80647701 0.15635396 0.64917493 0.0708586 ]
 [0.53587537 0.2812054  0.17943047 0.8617093  0.14988622]]


In [8]:
f = np.arange(0,30,7)
print(f)
g = np.linspace(0,30,7)
print(g)

[ 0  7 14 21 28]
[ 0.  5. 10. 15. 20. 25. 30.]


In [13]:
h = np.full((3,4), np.pi, dtype = 'complex')
print(h)

[[3.14159265+0.j 3.14159265+0.j 3.14159265+0.j 3.14159265+0.j]
 [3.14159265+0.j 3.14159265+0.j 3.14159265+0.j 3.14159265+0.j]
 [3.14159265+0.j 3.14159265+0.j 3.14159265+0.j 3.14159265+0.j]]
