[View in Colaboratory](https://colab.research.google.com/github/DeepankJain/Machine-Learning/blob/master/Numpy/Operations.ipynb)

In [0]:
import numpy as np

In [5]:
myarray = np.array([[1, 2, 3, 4], [5, 9, 6, 8], [1,9,14,2], [3,6,1,0]])
print(myarray)

[[ 1  2  3  4]
 [ 5  9  6  8]
 [ 1  9 14  2]
 [ 3  6  1  0]]


In [6]:
i = myarray[2, 0:3]
print(i)

[ 1  9 14]


In [7]:
j = myarray[[0,1,2], [0,1,2]]
print(j)

[ 1  9 14]


In [9]:
print(myarray.max())

14


In [10]:
print(myarray.max(axis=1))

[ 4  9 14  6]


In [11]:
print(myarray.sum())

74


In [12]:
print(myarray.sum(axis = 1))

[10 28 26 10]


In [13]:
print(myarray.cumsum(axis = 1))

[[ 1  3  6 10]
 [ 5 14 20 28]
 [ 1 10 24 26]
 [ 3  9 10 10]]


In [15]:
a = np.array([[1,2], [3,4]])
b = np.array([[11,12],[13,14]])
print(a*b)

[[11 24]
 [39 56]]


In [16]:
print(a.dot(b))

[[37 40]
 [85 92]]
